

export const users = [
  { id: 1, name: "Agricultural Innovations" },
  { id: 2, name: "Art Exhibitions" },
  { id: 3, name: "Artificial Intelligence" },
  { id: 4, name: "Astronomy Discoveries" },
  { id: 5, name: "Automotive News" },
  { id: 6, name: "Beauty Trends" },
  { id: 7, name: "Biotechnology" },
  { id: 8, name: "Business Strategies" },
  { id: 9, name: "Cinema Releases" },
  { id: 10, name: "Classical Music" },
  { id: 11, name: "Climate Change" },
  { id: 12, name: "Concerts" },
  { id: 13, name: "Culinary Arts" },
  { id: 14, name: "Cultural Festivals" },
  { id: 15, name: "Cybersecurity" },
  { id: 16, name: "Dance Performances" },
  { id: 17, name: "Digital Art" },
  { id: 18, name: "E-Sports Competitions" },
  { id: 19, name: "Economy" },
  { id: 20, name: "Education Innovations" },
  { id: 21, name: "Electronic Music" },
  { id: 22, name: "Emerging Technologies" },
  { id: 23, name: "Energy Solutions" },
  { id: 24, name: "Environmental Issues" },
  { id: 25, name: "Fashion" },
  { id: 26, name: "Film Festivals" },
  { id: 27, name: "Financial Markets" },
  { id: 28, name: "Fitness Trends" },
  { id: 29, name: "Food Technology" },
  { id: 30, name: "Gaming News" },
  { id: 31, name: "Genetic Research" },
  { id: 32, name: "Global Health Issues" },
  { id: 33, name: "Graphic Design Trends" },
  { id: 34, name: "Green Technology" },
  { id: 35, name: "Health Advances" },
  { id: 36, name: "Historical Discoveries" },
  { id: 37, name: "Indie Music" },
  { id: 38, name: "Industrial Design" },
  { id: 39, name: "Influencer Trends" },
  { id: 40, name: "Innovative Startups" },
  { id: 41, name: "Interior Design Trends" },
  { id: 42, name: "International Relations" },
  { id: 43, name: "Internet of Things" },
  { id: 44, name: "Jazz Music" },
  { id: 45, name: "Lifestyle Trends" },
  { id: 46, name: "Literary Releases" },
  { id: 47, name: "Machine Learning" },
  { id: 48, name: "Medical Breakthroughs" },
  { id: 49, name: "Modern Art" },
  { id: 50, name: "Musical Instruments" }
];
